include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/Platform.cmake")
if(NOT PICLOCATE_DEPENDENCY_CACHE)
  if(WIN32)
    set(_cache "$ENV{LOCALAPPDATA}/PicLocateBuild/cache")
  elseif(APPLE)
    set(_cache "$ENV{HOME}/Library/Caches/PicLocateBuild")
  elseif(DEFINED ENV{XDG_CACHE_HOME})
    set(_cache "$ENV{XDG_CACHE_HOME}/PicLocateBuild")
  else()
    set(_cache "$ENV{HOME}/.cache/PicLocateBuild")
  endif()
  set(PICLOCATE_DEPENDENCY_CACHE "${_cache}" CACHE PATH "Shared dependency cache")
endif()
file(TO_CMAKE_PATH "${PICLOCATE_DEPENDENCY_CACHE}" PICLOCATE_DEPENDENCY_CACHE)
if(NOT CPM_SOURCE_CACHE AND NOT DEFINED ENV{CPM_SOURCE_CACHE})
  set(CPM_SOURCE_CACHE "${PICLOCATE_DEPENDENCY_CACHE}/cpm" CACHE PATH "CPM download cache")
endif()
set(_cpm "${PICLOCATE_DEPENDENCY_CACHE}/CPM-0.43.2.cmake")
set(_cpm_sha 49a3bef91ceb65bb66d57255e12d1ffd22abc2f6408fa9fe4534c544a2f232aa)
if(EXISTS "${_cpm}")
  file(SHA256 "${_cpm}" _actual)
endif()
if(NOT _actual STREQUAL _cpm_sha)
  if(FETCHCONTENT_FULLY_DISCONNECTED)
    message(FATAL_ERROR "Pinned CPM bootstrap missing. Configure online once first.")
  endif()
  file(DOWNLOAD "https://github.com/cpm-cmake/CPM.cmake/releases/download/v0.43.2/CPM.cmake"
    "${_cpm}.part" EXPECTED_HASH SHA256=${_cpm_sha} TLS_VERIFY ON STATUS _status)
  list(GET _status 0 _code)
  if(NOT _code EQUAL 0)
    message(FATAL_ERROR "CPM download failed: ${_status}")
  endif()
  file(RENAME "${_cpm}.part" "${_cpm}")
endif()
include("${_cpm}")
set(PICLOCATE_QT_VERSION "6.11.2")
include("${CMAKE_CURRENT_LIST_DIR}/QtSdk.cmake")
set(PICLOCATE_QT_ROOT "" CACHE PATH "Optional existing Qt ${PICLOCATE_QT_VERSION} SDK")
if(NOT PICLOCATE_QT_ROOT)
  piclocate_qt_sdk("${PICLOCATE_PLATFORM_KEY}" PICLOCATE_QT_ROOT)
endif()
if(WIN32 AND PICLOCATE_ARCH STREQUAL "arm64" AND NOT QT_HOST_PATH)
  piclocate_qt_sdk(windows-x64 QT_HOST_PATH)
endif()
list(PREPEND CMAKE_PREFIX_PATH "${PICLOCATE_QT_ROOT}")
find_package(Qt6 ${PICLOCATE_QT_VERSION} EXACT REQUIRED COMPONENTS Core Gui Widgets Network Sql Concurrent)
if(BUILD_TESTING)
  find_package(Qt6 ${PICLOCATE_QT_VERSION} EXACT REQUIRED COMPONENTS Test)
endif()
set(ONNXRUNTIME_ROOT "" CACHE PATH "Optional compatible ONNX Runtime SDK")
if(NOT ONNXRUNTIME_ROOT)
  set(_ort_version 1.30.0)
  set(_ort_extension tgz)
  if(WIN32)
    set(_ort_name "win-${PICLOCATE_ARCH}")
    set(_ort_extension zip)
    if(PICLOCATE_ARCH STREQUAL "x64")
      set(_ort_sha c6ba983baf5681af108599675d2a89c2d145512d02de28aed0bff177cd0ba949)
    else()
      set(_ort_sha e53db8a50b23ae35be901cc93428baf997dc8d420333b097b2eae53d3ea9f2d3)
    endif()
  elseif(APPLE)
    if(PICLOCATE_ARCH STREQUAL "x64")
      # Last upstream release with Intel macOS binaries; uses the same CLIP checkpoint.
      set(_ort_version 1.23.2)
      set(_ort_name osx-x86_64)
      set(_ort_sha d10359e16347b57d9959f7e80a225a5b4a66ed7d7e007274a15cae86836485a6)
    else()
      set(_ort_name osx-arm64)
      set(_ort_sha 6ebb5062a934537c352937821f9fe9718e7de1a2db1122a93dd363ffd53a7012)
    endif()
  elseif(PICLOCATE_ARCH STREQUAL "x64")
    set(_ort_name linux-x64)
    set(_ort_sha a5ed5a3cac51fbb2e90da632ae43d19212faaa20e76484e62bcb7c23ddb3b3fd)
  else()
    set(_ort_name linux-aarch64)
    set(_ort_sha e16a27a8ed330bbc698df7330b0cf56e722f354e3bcc92118682c74ef3c3e3da)
  endif()
  CPMAddPackage(NAME PicLocateOnnxRuntime VERSION ${_ort_version} DOWNLOAD_ONLY YES
    URL "https://github.com/microsoft/onnxruntime/releases/download/v${_ort_version}/onnxruntime-${_ort_name}-${_ort_version}.${_ort_extension}"
    URL_HASH SHA256=${_ort_sha})
  set(ONNXRUNTIME_ROOT "${PicLocateOnnxRuntime_SOURCE_DIR}")
endif()
find_path(_ort_include onnxruntime_cxx_api.h PATHS "${ONNXRUNTIME_ROOT}/include" NO_DEFAULT_PATH REQUIRED)
find_library(_ort_library onnxruntime PATHS "${ONNXRUNTIME_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
add_library(ONNXRuntime::ONNXRuntime SHARED IMPORTED GLOBAL)
set_target_properties(ONNXRuntime::ONNXRuntime PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_ort_include}")
if(WIN32)
  set_target_properties(ONNXRuntime::ONNXRuntime PROPERTIES
    IMPORTED_IMPLIB "${_ort_library}" IMPORTED_LOCATION "${ONNXRUNTIME_ROOT}/lib/onnxruntime.dll")
else()
  set_target_properties(ONNXRuntime::ONNXRuntime PROPERTIES IMPORTED_LOCATION "${_ort_library}")
endif()
file(WRITE "${CMAKE_BINARY_DIR}/dependency-paths.json"
  "{\n  \"qt\": \"${PICLOCATE_QT_ROOT}\",\n  \"ort\": \"${ONNXRUNTIME_ROOT}\",\n  \"cache\": \"${PICLOCATE_DEPENDENCY_CACHE}\"\n}\n")
