option(PICLOCATE_BUNDLE_MODELS "Fetch and bundle the verified local CLIP model pack" ON)
if(PICLOCATE_BUNDLE_MODELS)
  file(READ "${PROJECT_SOURCE_DIR}/scripts/models.json" _manifest)
  string(JSON _base GET "${_manifest}" base_url)
  string(JSON _count LENGTH "${_manifest}" files)
  math(EXPR _last "${_count} - 1")
  set(PICLOCATE_MODEL_DIR "${PICLOCATE_DEPENDENCY_CACHE}/models/clip-b32-d15189d7")
  foreach(_index RANGE ${_last})
    foreach(_field name remote sha256)
      string(JSON _${_field} GET "${_manifest}" files ${_index} ${_field})
    endforeach()
    if(NOT WIN32 AND _name STREQUAL "vision_model_fp16.onnx")
      continue()
    endif()
    CPMAddPackage(NAME PicLocateModel${_index} VERSION 1.0 DOWNLOAD_ONLY YES DOWNLOAD_NO_EXTRACT YES
      URL "${_base}${_remote}" URL_HASH SHA256=${_sha256})
    file(MAKE_DIRECTORY "${PICLOCATE_MODEL_DIR}")
    file(COPY_FILE "${PicLocateModel${_index}_SOURCE_DIR}/${_name}" "${PICLOCATE_MODEL_DIR}/${_name}" ONLY_IF_DIFFERENT)
  endforeach()
  if(WIN32)
    install(DIRECTORY "${PICLOCATE_MODEL_DIR}/" DESTINATION ${PICLOCATE_RESOURCE_DEST}/models)
  else()
    install(DIRECTORY "${PICLOCATE_MODEL_DIR}/" DESTINATION ${PICLOCATE_RESOURCE_DEST}/models PATTERN "vision_model_fp16.onnx" EXCLUDE)
  endif()
endif()
