if(WIN32)
  # The portable executable and DLLs share the package root; plugins have one subdirectory.
  install(CODE "execute_process(COMMAND \"${PICLOCATE_QT_ROOT}/bin/windeployqt.exe\"
    --qtpaths \"${PICLOCATE_QT_ROOT}/bin/qtpaths.exe\"
    --release --no-translations --no-compiler-runtime --no-opengl-sw
    --no-system-d3d-compiler --no-system-dxc-compiler
    --dir \"\${CMAKE_INSTALL_PREFIX}\" --libdir \"\${CMAKE_INSTALL_PREFIX}\"
    --plugindir \"\${CMAKE_INSTALL_PREFIX}/plugins\" \"\${CMAKE_INSTALL_PREFIX}/PicLocate.exe\"
    COMMAND_ERROR_IS_FATAL ANY)
    file(WRITE \"\${CMAKE_INSTALL_PREFIX}/qt.conf\" \"[Paths]\\nPlugins=plugins\\n\")")
  set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION ".")
  include(InstallRequiredSystemLibraries)
else()
  set(CMAKE_INSTALL_BINDIR bin)
  set(CMAKE_INSTALL_LIBDIR lib)
  qt_generate_deploy_app_script(TARGET PicLocate OUTPUT_SCRIPT _deploy NO_TRANSLATIONS)
  install(SCRIPT ${_deploy})
  if(NOT APPLE)
    install(FILES resources/piclocate.desktop DESTINATION share/applications)
    install(FILES resources/piclocate.svg DESTINATION share/icons/hicolor/scalable/apps)
    install(PROGRAMS scripts/PicLocate.sh DESTINATION .)
  endif()
endif()
# Redistributed Qt binaries carry the matching source and license texts.
file(READ "${PROJECT_SOURCE_DIR}/scripts/qt-sources.json" _qt_sources)
string(JSON _count LENGTH "${_qt_sources}")
math(EXPR _last "${_count} - 1")
foreach(_index RANGE ${_last})
  foreach(_field name url sha256)
    string(JSON _${_field} GET "${_qt_sources}" ${_index} ${_field})
  endforeach()
  CPMAddPackage(NAME PicLocateQtSource${_index} VERSION ${PICLOCATE_QT_VERSION} DOWNLOAD_ONLY YES DOWNLOAD_NO_EXTRACT YES
    URL "${_url}" URL_HASH SHA256=${_sha256})
  set(_archive "${PicLocateQtSource${_index}_SOURCE_DIR}/${_name}")
  string(REPLACE ".tar.xz" "" _module "${_name}")
  set(_licenses "${PICLOCATE_DEPENDENCY_CACHE}/licenses/${_module}")
  if(NOT EXISTS "${_licenses}/${_module}/LICENSES")
    file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${_licenses}" PATTERNS "${_module}/LICENSES/*")
  endif()
  install(FILES "${_archive}" DESTINATION ${PICLOCATE_RESOURCE_DEST}/third-party-source)
  install(DIRECTORY "${_licenses}/${_module}/LICENSES/" DESTINATION "${PICLOCATE_RESOURCE_DEST}/licenses/${_module}")
endforeach()
if(NOT WIN32)
  set(CPACK_PACKAGE_NAME PicLocate)
  set(CPACK_PACKAGE_VENDOR "PicLocate contributors")
  set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
  set(CPACK_PACKAGE_FILE_NAME "PicLocate-${PROJECT_VERSION}-${PICLOCATE_PLATFORM_KEY}")
  set(CPACK_PACKAGE_DIRECTORY "${PROJECT_SOURCE_DIR}/dist/packages")
  set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
  if(APPLE)
    set(CPACK_GENERATOR DragNDrop)
    set(CPACK_DMG_VOLUME_NAME PicLocate)
  else()
    set(CPACK_GENERATOR TGZ)
  endif()
  include(CPack)
endif()
