include_guard(GLOBAL)
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
  message(FATAL_ERROR "PicLocate requires a 64-bit target (x64 or ARM64).")
endif()
set(_processor "${CMAKE_SYSTEM_PROCESSOR}")
if(APPLE AND CMAKE_OSX_ARCHITECTURES)
  set(_processor "${CMAKE_OSX_ARCHITECTURES}")
elseif(MSVC AND CMAKE_CXX_COMPILER_ARCHITECTURE_ID)
  set(_processor "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")
endif()
string(TOLOWER "${_processor}" _processor)
if(_processor MATCHES "^(amd64|x86_64|x64)$")
  set(PICLOCATE_ARCH x64)
elseif(_processor MATCHES "^(arm64|aarch64)$")
  set(PICLOCATE_ARCH arm64)
else()
  message(FATAL_ERROR "Unsupported target: ${_processor}. Build one x64 or ARM64 architecture at a time.")
endif()
set(PICLOCATE_RESOURCE_DEST ".")
set(PICLOCATE_BINARY_DEST ".")
if(WIN32)
  if(NOT MSVC)
    message(FATAL_ERROR "The Windows SDK packages require MSVC.")
  endif()
  set(PICLOCATE_PLATFORM windows)
elseif(APPLE)
  set(PICLOCATE_PLATFORM macos)
  set(PICLOCATE_RESOURCE_DEST "PicLocate.app/Contents/Resources")
  # Match the deployment floors embedded in the pinned upstream ONNX dylibs.
  if(PICLOCATE_ARCH STREQUAL "arm64")
    set(_mac_minimum 14.0)
  else()
    set(_mac_minimum 13.4)
  endif()
  if(NOT CMAKE_OSX_DEPLOYMENT_TARGET)
    set(CMAKE_OSX_DEPLOYMENT_TARGET "${_mac_minimum}" CACHE STRING "Minimum macOS version" FORCE)
  elseif(CMAKE_OSX_DEPLOYMENT_TARGET VERSION_LESS _mac_minimum)
    message(FATAL_ERROR "The pinned ${PICLOCATE_ARCH} ONNX runtime requires macOS ${_mac_minimum} or newer.")
  endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(PICLOCATE_PLATFORM linux)
  set(PICLOCATE_BINARY_DEST bin)
  set(PICLOCATE_RESOURCE_DEST "share/PicLocate")
else()
  message(FATAL_ERROR "Supported desktop targets: Windows, macOS and Linux.")
endif()
set(PICLOCATE_PLATFORM_KEY "${PICLOCATE_PLATFORM}-${PICLOCATE_ARCH}")
