function(piclocate_qt_sdk platform result)
  if(platform MATCHES "^macos-")
    set(platform macos)
  endif()
  file(READ "${PROJECT_SOURCE_DIR}/scripts/qt-sdks.json" _manifest)
  string(JSON _subdir GET "${_manifest}" "${platform}" subdir)
  string(JSON _count LENGTH "${_manifest}" "${platform}" archives)
  math(EXPR _last "${_count} - 1")
  set(_root "${PICLOCATE_DEPENDENCY_CACHE}/qt-${PICLOCATE_QT_VERSION}-${platform}")
  file(MAKE_DIRECTORY "${PICLOCATE_DEPENDENCY_CACHE}")
  file(LOCK "${PICLOCATE_DEPENDENCY_CACHE}/qt-${PICLOCATE_QT_VERSION}-${platform}.lock" GUARD FUNCTION TIMEOUT 900)
  foreach(_index RANGE ${_last})
    foreach(_field name url sha256)
      string(JSON _${_field} GET "${_manifest}" "${platform}" archives ${_index} ${_field})
    endforeach()
    set(_package "PicLocate_${platform}_${_name}")
    CPMAddPackage(NAME ${_package} VERSION ${PICLOCATE_QT_VERSION} DOWNLOAD_ONLY YES
      URL "${_url}" URL_HASH SHA256=${_sha256})
    if(NOT EXISTS "${_root}/.${_name}-${_sha256}")
      set(_source "${${_package}_SOURCE_DIR}")
      if(NOT _source OR NOT IS_DIRECTORY "${_source}")
        message(FATAL_ERROR "Pinned Qt SDK module ${_name} is unavailable; configure online once first.")
      endif()
      if(_name STREQUAL "qttranslations")
        # windeployqt reads its deployment catalog even with --no-translations.
        # This SDK data stays outside the application package.
        if(EXISTS "${_source}/${PICLOCATE_QT_VERSION}/translations")
          set(_source "${_source}/${PICLOCATE_QT_VERSION}")
        endif()
        if(EXISTS "${_source}/translations")
          file(COPY "${_source}/translations" DESTINATION "${_root}")
        else()
          if(NOT EXISTS "${_source}/catalogs.json")
            message(FATAL_ERROR "Unexpected Qt deployment catalog layout: ${_source}")
          endif()
          file(COPY "${_source}/" DESTINATION "${_root}/translations")
        endif()
        file(WRITE "${_root}/.${_name}-${_sha256}" "${_sha256}\n")
        continue()
      endif()
      if(_name STREQUAL "icu")
        # FetchContent strips the archive's single lib/ parent directory.
        file(GLOB _icu "${_source}/libicu*.so*")
        if(_icu)
          file(COPY ${_icu} DESTINATION "${_root}/lib")
          file(WRITE "${_root}/.${_name}-${_sha256}" "${_sha256}\n")
          continue()
        endif()
      endif()
      if(EXISTS "${_source}/${PICLOCATE_QT_VERSION}/${_subdir}")
        set(_source "${_source}/${PICLOCATE_QT_VERSION}/${_subdir}")
      elseif(EXISTS "${_source}/${_subdir}")
        set(_source "${_source}/${_subdir}")
      elseif(NOT EXISTS "${_source}/lib" AND NOT EXISTS "${_source}/plugins" AND NOT EXISTS "${_source}/bin")
        message(FATAL_ERROR "Unexpected Qt archive layout: ${_source}")
      endif()
      file(COPY "${_source}/" DESTINATION "${_root}")
      file(WRITE "${_root}/.${_name}-${_sha256}" "${_sha256}\n")
    endif()
  endforeach()
  file(WRITE "${_root}/bin/qt.conf" "[Paths]\nPrefix=..\n")
  set(${result} "${_root}" PARENT_SCOPE)
endfunction()
